### ISSUE TITLE
.env file not loaded

### ISSUE THREAD

**Issue by ArchebasovVl** [cuprum-acid/Collega-bot#9]
## Description

The current version of code missing `.env` file loading, so `os.environ` does not contain necessary keys when run locally.

## Possible solutions

1. Use an additional package like [python-dotenv](https://pypi.org/project/python-dotenv/).
2. Add info into readme if the keys are managed manually.

**Comment by cuprum-acid** [comment]
Thanks for noticing, but pushing `.env` files in git repostitory considered to be bad practice due to security issues. That's why we have `.env.example` that should provide you all nessesary information about content of `.env` file.

Also, refer to `README.md` for more information.

**Comment by ArchebasovVl** [comment]
Is our code supposed to automatically load information from `.env` file? This doesn't happen, though i have file named `.env` in the root directory of the project:

![image](https://github.com/user-attachments/assets/b7e4cee5-5aeb-4fdf-a887-d286f7130916)


I've seen that we can add key-values from a file using python-dotnev:
```
from dotenv import load_dotenv
import os

load_dotenv()  # Load the .env file

api_key = os.environ.get('API_KEY')
```
but the application is running in docker somehow without loading the information from code.

I can add key-values to my os environment manually in terminal if you did this when you have started a docker container. But if you did, i am not sure how to use `.env` file.
